services:
  - type: web
    name: cristal-gitworker
    env: python
    plan: free
    branch: main
    buildCommand: ""
    startCommand: python app.py
    envVars:
      - key: GITHUB_TOKEN
        value: your_github_token_here
